name: 🧹 Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:     # Manual trigger support

jobs:
  cleanup_old_runs:
    runs-on: ubuntu-latest

    permissions:
      actions: write  # Required to delete runs
      contents: read

    steps:
      - name: Delete workflow runs older than 2 days
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflows = await github.rest.actions.listRepoWorkflows({ owner, repo });

            for (const workflow of workflows.data.workflows) {
              const runs = await github.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id: workflow.id,
                per_page: 100,
              });

              for (const run of runs.data.workflow_runs) {
                const createdAt = new Date(run.created_at);
                const twoDaysAgo = new Date(Date.now() - 2 * 24 * 60 * 60 * 1000); // 48 hours ago

                if (createdAt < twoDaysAgo) {
                  console.log(`Deleting run ${run.id} from ${createdAt}`);
                  await github.rest.actions.deleteWorkflowRun({
                    owner,
                    repo,
                    run_id: run.id,
                  });
                }
              }
            }
